# Set working directory to parent directory (i.e: main directory for this project)
# Snakemake complains sometimes when working with files in parent directories...
import os
os.chdir(os.path.dirname(os.getcwd()))  # set working dir to parent dir
print(os.getcwd())

# Global variables
# TODO - move these to a config file
singularity: "singularity/container.sif"
PROTEOMES = 'data/proteomes'
ALL_V_ALL_ALGO = 'blast'
REFERENCE_SPECIES = 'E_brev'
PFAM_LIB = "data/pfam/Pfam-A.hmm"

rule all:
	input: "results/hmmscan"

rule run_orthofinder:
	input: PROTEOMES
	output: directory("results/OrthoFinder")
	shell:
		"""
		orthofinder -f {input} -og -S {ALL_V_ALL_ALGO} -o {output} -n OrthoFinder
		"""

rule get_single_copy_orthogroups:
	# From Orthogroups.tsv from OrthoFinder, filter the orthogroups to
	# those with a single-copy ortholog in yeast and a single-copy
	# ortholog from *any* other species
	input: "results/OrthoFinder"
	output: "results/single_copy_orthogroups.csv", "resources/orthogroups_for_hmmscan"
	shell:
		"""
		Rscript workflow/scripts/get_single_copy_orthogroups.R {input} {REFERENCE_SPECIES} {output}
		"""
		
# TODO - parallelize this code
rule run_hmmscan_on_single_copy_orthogroups:
	input: "resources/orthogroups_for_hmmscan"
	output: directory("results/hmmscan")
	shell:
		"""
		mkdir {output}
		
		while read orthogroup; do
			hmmscan -o results/hmmscan/"$orthogroup" \
			--cut_ga {PFAM_LIB} \
			results/OrthoFinder/Results_OrthoFinder/Orthogroup_Sequences/"$orthogroup".fa
		done < {input}
		"""
	
rule run_cath_resolve_hits:
	input: ""
	
rule align_ortholog_domain_architectures:
	input: ""

rule singularity_test:
	# run "snakemake --cores all --use-singularity singularity_test"
	# to ensure all required software can be called without error from
	# the Singularity container
	shell:
        	"""
        	cath-resolve-hits -h
        	blastp -help
        	diamond help
        	hmmscan -h
        	orthofinder -h
        	R --slave -e 'library(tidyverse)'
        
        	echo -e '\n\n'
        	echo '#########################################################'
        	echo '\n'
        	echo 'Singularity container successfully deployed in Snakemake!'
        	echo '\n'
        	echo '#########################################################'
        	echo -e '\n\n'
        	"""
